/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import persistencia.CadFunc;
import persistencia.DAOFunc;

/**
 *
 * @author Wallace
 */
public class Cadastro_LoginBNS extends javax.swing.JFrame {

     String teste;
    /**
     * Creates new form CadastroBNS
     */
    public Cadastro_LoginBNS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtUsuarioLogin = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        pwdSenha1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtNomeFull = new javax.swing.JTextField();
        pwdSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        txtUsuarioLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUsuarioLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioLoginFocusLost(evt);
            }
        });
        jPanel1.add(txtUsuarioLogin);
        txtUsuarioLogin.setBounds(230, 150, 250, 40);
        txtUsuarioLogin.setText("Usuario:");
        txtUsuarioLogin.setFont(new Font("Century Ghotic", Font.ITALIC, 24));

        btnEntrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar);
        btnEntrar.setBounds(230, 310, 250, 30);

        pwdSenha1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        pwdSenha1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pwdSenha1);
        pwdSenha1.setBounds(230, 220, 250, 40);

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        btnCadastrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastrar);
        btnCadastrar.setBounds(310, 330, 120, 40);

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel2.add(txtEmail);
        txtEmail.setBounds(110, 170, 320, 40);
        if(txtEmail.getText().length() == 0){
            txtEmail.setText("Email");
        }
        txtEmail.setFont(new Font("Century Ghotic", Font.ITALIC, 12));

        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        jPanel2.add(txtUser);
        txtUser.setBounds(110, 110, 320, 40);
        if(txtUser.getText().length() == 0){
            txtUser.setText("Nome do usuário");
        }
        txtUser.setFont(new Font("Century Ghotic", Font.ITALIC, 12));

        txtNomeFull.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFullFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFullFocusLost(evt);
            }
        });
        jPanel2.add(txtNomeFull);
        txtNomeFull.setBounds(110, 50, 320, 40);
        if(txtNomeFull.getText().length() == 0){
            txtNomeFull.setText("Nome Completo");
        }
        txtNomeFull.setFont(new Font("Century Ghotic", Font.ITALIC, 12));
        jPanel2.add(pwdSenha);
        pwdSenha.setBounds(110, 250, 320, 40);
        pwdSenha.getAccessibleContext().setAccessibleDescription("Senha");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VendasBNS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(500, 50, 210, 60);

        jLabel2.setText("Sua senha aqui:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 230, 82, 16);

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 730, 480);

        setSize(new java.awt.Dimension(745, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        CadFunc func;
        DAOFunc dao;
        boolean retorno;

        if (txtNomeFull.getText().equals("") || txtNomeFull.getText().equals("Nome Completo")) {
            JOptionPane.showMessageDialog(null, "Campo nome vazio!");
            txtNomeFull.requestFocus();
        } else if (txtUser.getText().equals("") || txtUser.getText().equals("Nome do usuário")) {
            JOptionPane.showMessageDialog(null, "Campo User vazio!");
            txtUser.requestFocus();
        } else if (txtEmail.getText().equals("") || txtEmail.getText().equals("Email")) {
            JOptionPane.showMessageDialog(null, "O Campo Email vazio!");
            txtEmail.requestFocus();
        } else if (pwdSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Senha vazio!");
            pwdSenha.requestFocus();
        } else {
            func = new CadFunc();
            func.setNome(txtNomeFull.getText());
            func.setUsuario(txtUser.getText());
            func.setEmail(txtEmail.getText());
            func.setSenha(pwdSenha.getText());
            dao = new DAOFunc();
            retorno = dao.conectar();
            if (retorno == true) {
                int r = dao.salvar(func);
                if (r == 1) {
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado!");

                }

            } else {
                JOptionPane.showMessageDialog(null, "Erro de conexão!! Contate o Administrador do programa. ");
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

// Acão textbox Tela cadastro
    private void txtNomeFullFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFullFocusGained
        if (txtNomeFull.getText().equals("Nome Completo")) {
            txtNomeFull.setText("");
        }
    }//GEN-LAST:event_txtNomeFullFocusGained

    private void txtNomeFullFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFullFocusLost
        if (txtNomeFull.getText().equals("")) {
            txtNomeFull.setText("Nome Completo");
            txtNomeFull.setFont(new Font("Century Ghotic", Font.ITALIC, 12));
            txtNomeFull.setSelectedTextColor(Color.red);
        }
    }//GEN-LAST:event_txtNomeFullFocusLost

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        if (txtUser.getText().equals("Nome do usuário")) {
            txtUser.setText("");
        }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        if (txtUser.getText().equals("")) {
            txtUser.setText("Nome do usuário");
            txtUser.setFont(new Font("Century Ghotic", Font.ITALIC, 12));
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Email")) {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Email");
            txtEmail.setFont(new Font("Century Ghotic", Font.ITALIC, 12));
        }
    }//GEN-LAST:event_txtEmailFocusLost
//Fechando acão textbox tela cadastro    

    //Ação textbox Tela login
    private void txtUsuarioLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioLoginFocusGained
        if (txtUsuarioLogin.getText().equals("Usuario:")) {
            txtUsuarioLogin.setText("");
            
        }
    }//GEN-LAST:event_txtUsuarioLoginFocusGained
  
    //Botão Entrar
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
       
        try {
            String url = "jdbc:mysql://localhost:3306/vendasbns";
            String user = "root";
            String password = "WALL01101FfX7ss";

            Connection con;
            PreparedStatement st;
            ResultSet rs;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, user, password);
            st = con.prepareStatement("SELECT * FROM cadastro WHERE usuario = ? AND senha = ?");
            st.setString(1, txtUsuarioLogin.getText());
            st.setString(2, pwdSenha1.getText());
            rs = st.executeQuery();
            if (txtUsuarioLogin.getText().toString().equals("") && pwdSenha.getText().toString().equals("")) {
                txtUsuarioLogin.setBackground(Color.red);
                pwdSenha1.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Os campos precisam estar prenchidos");
                txtUsuarioLogin.setBackground(Color.white);
                pwdSenha1.setBackground(Color.white);
            } else if (rs.next()) {
               //teste =  rs.getString("nome");
                TelaInicial t = new TelaInicial();
                t.show();
                this.setVisible(false);
            } else {

                txtUsuarioLogin.setBackground(Color.red);
                pwdSenha1.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Usuario ou Senha incorretos");
                txtUsuarioLogin.setBackground(Color.white);
                pwdSenha1.setBackground(Color.white);
                txtUsuarioLogin.requestFocus();
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao acessar banco de dados,\n favor contatar o administrador do sistema e informar o erro: " + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed
    //Fechando botão entrar
    
    //Ação TextBox TelaLogin
    private void txtUsuarioLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioLoginFocusLost
        if (txtUsuarioLogin.getText().equals("")) {
            txtUsuarioLogin.setText("Usuario:");
            txtUsuarioLogin.setFont(new Font("Century Ghotic", Font.ITALIC, 24));
        }
    }//GEN-LAST:event_txtUsuarioLoginFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_LoginBNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_LoginBNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_LoginBNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_LoginBNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_LoginBNS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField pwdSenha;
    private static transient javax.swing.JPasswordField pwdSenha1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeFull;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
